export const TEST_PLOTS: string[] = [
  "A clockmaker whose clocks run backwards and age the wearer in reverse",
  "Two scientists fall in love over a discovery that could end the world",
  "A blind painter who sees colour only in her dreams",
  "A postman who delivers letters addressed to people who no longer exist",
  "A child who can freeze time, but only when she is laughing",
  "An astronaut stranded on Mars befriends a rover that has gained sentience",
  "A chef who cooks meals that reveal the diner's deepest secret",
  "A musician who discovers her lullabies are keeping a god asleep",
  "A bridge builder who realises every bridge he builds connects two feuding families",
  "A florist whose flowers bloom only when someone nearby is lying",
  "A sailor who keeps finding the same message in a bottle",
  "An architect hired to design a building that must never cast a shadow",
  "A teacher whose students never forget anything she says — literally",
  "A barber whose haircuts accidentally change a person's personality",
  "A magician who lost real magic and must fake it to keep people's hope alive",
  "A veterinarian who can speak to animals but cannot tell anyone what they say",
  "A cartographer mapping the territory of someone else's grief",
  "A spy who has forgotten which side she works for",
  "A ghost who haunts a house but keeps falling asleep on the job",
  "A mathematician who discovers infinity has an edge",
  "A beekeeper whose hive produces honey that tastes like forgotten memories",
  "A sculptor whose statues weep real tears when no one is watching",
  "A pilot who flies the same route but lands in a different decade each time",
  "A lawyer who defends clients she knows are innocent of a crime they did commit",
  "A janitor in a museum who is the only one who knows the art is alive",
  "A seamstress who stitches constellations into coats to guide lost travellers",
  "A fisherman who catches the same fish every day and releases it",
  "A historian discovering that every civilization ended for the same reason",
  "Two twins race to give back a gift that grants wishes but punishes regret",
  "A candlemaker whose candles, when lit, revive old conversations",
  "A river god bargains with a drought-stricken village but wants only stories",
  "A telescope that shows what a star looked like the moment it died",
  "A retired soldier who finds she left a version of herself behind in every war",
  "A baker who bakes bread for the dead to eat on their way somewhere else",
  "A gardener tending a forest of trees, each one a person turned to wood",
  "A locksmith who finds every lock she opens contains a different universe",
  "A lighthouse keeper on a lighthouse that guides travellers between worlds",
  "A child raised by clocks who measures love in seconds",
  "An island that migrates with the seasons, carrying its people to warmth",
  "A poet whose words rearrange reality but only when spoken aloud at dawn",
  "A mirror maker who discovers her mirrors show who you were, not who you are",
  "A sommelier who can taste the emotional history of a wine's vineyard",
  "An archivist cataloguing dreams that were never dreamed",
  "A nomad who carries a city on her back and sets it down wherever she rests",
  "A pharmacist whose medicines cure the wrong illness but the right sorrow",
  "A cartoonist whose drawings escape the page and reorganise the city",
  "A geographer who finds that every map she draws changes the land it depicts",
  "A hermit who discovers the mountain she lives on is a sleeping giant",
  "A translator who realises two languages are gradually becoming one",
  "A juggler who juggles futures and must choose which one to drop",
  "A watchman guarding a door that must never be opened but never ignored",
  "A diver who can breathe underwater but only when she is afraid",
  "A birdwatcher who begins to forget human language and remember bird song",
  "A doctor who can only heal patients by taking their illness into herself",
  "A weaver whose tapestry, when completed, will depict the end of the world",
  "A ferryman whose river flows not between banks but between lifetimes",
  "A jeweller who discovers every gem she cuts contains a compressed life",
  "A tinker who travels a land repairing broken machines, each one a metaphor",
  "A shepherd herding clouds across a sky that is running out of room",
  "An innkeeper whose inn appears only to travellers who truly need rest",
  "A vintner who bottles storms instead of wine",
  "A stone carver chiselling a door into a cliff face that slowly opens",
  "A merchant trading in obsolete words that still remember their meaning",
  "A papermaker whose paper remembers every word ever written on anything like it",
  "A cartographer hired to map a country that is slowly forgetting itself",
  "A bell founder whose bells summon the specific person who is needed",
  "A lamplighter in a city where darkness has developed a sense of humour",
  "An engineer designing a machine to measure kindness",
  "A rope maker whose ropes, when braided, tie people to their own futures",
  "A dreamcatcher who catches too much and begins to dream someone else's life",
  "A moth collector who realises every moth is carrying a human secret",
  "A tide caller who calls the tide in but cannot call it back",
  "A seedkeeper in a vault beneath a dying glacier",
  "A falconer whose falcon returns with messages from people who have not sent them",
  "A water diviner searching for water on a world that has forgotten rain",
  "A puppet master whose puppets begin to perform plays she has not written",
  "A soil scientist who discovers the earth beneath a battlefield is still afraid",
  "A chandler whose candles each contain a preserved wish from someone long dead",
  "A glassblower whose glass, when broken, plays the sound the maker was feeling",
  "A town crier announcing events that have not happened yet but will",
  "A night watchman in a library where the books rearrange themselves by mood",
  "A seed merchant who sells seeds that grow into whatever the buyer most fears",
  "A letter writer composing apologies on behalf of people who cannot apologise",
  "A bookbinder binding a book that rewrites its contents when closed",
  "A net mender whose nets, when whole, can catch lost time",
  "A mapmaker who maps the faces of people who have been forgotten",
  "A cantor whose singing opens a door in the air to a place beyond grief",
  "A navigator who navigates by stars that have not yet been named",
  "A keeper of keys who has forgotten which door each key belongs to",
  "A cheese maker whose cheese, when aged long enough, begins to speak",
  "A dyer whose dyes change colour depending on the moral character of the wearer",
  "A grain counter in a granary where the grain multiplies overnight",
  "A barrel maker whose barrels, when sealed, preserve not wine but moments",
  "A lighthouse keeper who discovers the light she tends guides lost stars, not ships",
  "Two rival chefs must cook together to lift a curse on their village",
  "A cartographer hired to map a city that rearranges itself every night",
  "A time traveler who keeps arriving exactly five minutes too late",
  "A detective who solves every crime using only their sense of smell",
  "A librarian who finds that books rewrite themselves after midnight",
  "A submarine crew that discovers a civilisation living inside a whale",
  "A robot given one day of free will uses it to become a painter",
  "A musician whose songs accidentally change the local weather",
  "A child who befriends the shadow that refuses to follow them",
];
